---
title: "Fetch Limited Datas"
author: "CLETZ Laura"
date: "2025-03-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


In order to fetch only a limited number of datas (20 000 lines per files), we need to source the file that contains the useful functions:
```{r}
source('R/fetch_data.R')
```

Using the function created in the *R/fetch_data.R* file, we extract a limited lines of each files from the PlantNet-CrowdSWE database on **Zenodo**.
```{r}
subDir <- "limited_data"
mainDir <- getwd()
dir_path <- file.path(mainDir, subDir)
if (!dir.exists(dir_path)) {
  dir.create(dir_path, recursive = TRUE, showWarnings = FALSE)
}


zip_url <- "https://zenodo.org/record/10782465/files/plantnet_swe.zip"
zip_path <- file.path(tempdir(), "plantnet_swe.zip")


download.file(zip_url, zip_path, mode = "wb")

target_files <- c("zenodo/aggregation/ai_answers.json",
                  "zenodo/aggregation/ai_classes.json",
                  "zenodo/aggregation/ai_scores.json",
                  "zenodo/converters/classes.json",
                  "zenodo/converters/tasks.json",
                  "zenodo/answers/ground_truth.txt")

output_files <- file.path(dir_path, basename(target_files))


unique_dirs <- unique(dirname(output_files))
for (dir in unique_dirs) {
  if (!dir.exists(dir)) {
    dir.create(dir, recursive = TRUE, showWarnings = FALSE)
  }
}

unzip(zip_path, files = target_files, exdir = dir_path, junkpaths = TRUE)


for (file in output_files) {
  extract_limited_lines(file)
}
```
